# -*- coding: utf-8 -*-
"""A01796723_A6.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0qDob76booLJ8ImOIR_wDOSWivDnGNk
"""

!pip install flake8

import os
import datetime as dt


class room:
    def __init__(self,number,size,beds,price):
        self.numder = number
        self.size = size
        self.beds = beds
        self.price = price


class hotel:
    def __init__(self,name,rooms,desc):
        self.name = name
        self.rooms = rooms
        self.descrption = desc
    def create_hotel(name,rooms,desc):
        return hotel(name,rooms,desc)
    def delete_hotel():
        self.name = null
        self.rooms = null
    def display_info():
        return self.descrption
    def modify_info(name,rooms,desc):
        self.name = name
        self.rooms = rooms
        self.descrption = desc
    def cancel_reservation(reser):
        reser.cancel()


class customer:
    def __init__(self,name,nroom,rtype,fn,ln):
        self.name = name
        self.num_rooms = nroom
        self.room_type = rtype
        self.first_night = fn
        self.last_night = ln
    def create_customer(name,nroom,rtype,fn,ln):
        return customer(name,nroom,rtype,fn,ln)
    def modify_info(name,nroom,rtype,fn,ln):
        self.name = name
        self.num_rooms = nroom
        self.room_type = rtype
        self.first_night = fn
        self.last_night = ln


class reservation:
    def __init__(self,client,rooms):
        self.client = client
        self.rooms = rooms
    def create_reservation(h,c):
        days_stay = (c-last_night-c.first_night).days
        res_rooms = {}
        for i in c.num_rooms:
            for r in h.rooms:
                if r.size == c.room_type[i]:
                    res_rooms.append(r)
        return reservation(c,res_rooms)


# creamos habitaciones en los primeros 4 pisos
Habitaciones = []
for i in range(4):
    for j in range(25):
        if i == 0:
            Habitaciones.append(room((i+1)*100+j,'small',1,1000))
        elif i >= 1:
            if j % 2 == 0:
                Habitaciones.append(room((i+1)*100+j,'medium',2,1500))
            else:
                Habitaciones.append(room((i+1)*100+j,'medium',1,1500))

Mihotel = hotel('Mi Hotel',Habitaciones,'Hotel generico en con 100 habitaciones')

Clientes = []
Clientes.append(customer('Juan Perez',1,['small'],dt.datetime(2026,2,23),dt.datetime(2026,2,24)))
Clientes.append(customer('Anna Gomez',1,['medium'],dt.datetime(2026,2,23),dt.datetime(2026,2,24)))
Clientes.append(customer('Luis Suarez',2,['medium'],dt.datetime(2026,2,25),dt.datetime(2026,2,27)))
Clientes.append(customer('Maria Gil',5,['small'],dt.datetime(2026,2,24),dt.datetime(2026,2,26)))

Reservaciones = []
for c in Clientes:
    print(Mihotel.rooms)
    Reservaciones.append(reservation(c,[]).create_reservation(Mihotel.rooms,c))